name: build

on:
  push:
    branches-ignore:
      - "docs"
  pull_request:
    branches-ignore:
      - "docs"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: 'Windows x64'
            os: windows-latest
            triplet: x64-windows
            suffix: 'windows-win64'
          - name: 'Linux x64'
            os: ubuntu-latest
            triplet: x64-linux
            suffix: 'linux-amd64'
          - name: 'Mac OSX x64'
            os: macos-latest
            triplet: x64-osx
            suffix: 'osx-amd64'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Run apt"
        if: runner.os == 'Linux'
        run: sudo apt install -y pkg-config ninja-build

      - name: "Run homebrew"
        if: runner.os == 'macOS'
        run: brew install ninja

      - uses: microsoft/setup-msbuild@v2
        if: runner.os == 'Windows'
        with:
          msbuild-architecture: ${{ runner.arch }}

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ runner.tool_cache }}/vcpkg"
          vcpkgGitCommitId: "6f29f12e82a8293156836ad81cc9bf5af41fe836" # 2025.01.13
          runVcpkgInstall: true
          vcpkgJsonGlob: 'vcpkg.json'

      - uses: lukka/run-cmake@v10
        with:
          workflowPreset: ${{ matrix.suffix }}

      - name: "Run cmake(install)"
        run: |
          cmake --build --preset "${{ matrix.triplet }}-debug" --target install

      - name: "List runtime dependencies(Linux)"
        if: runner.os == 'Linux'
        run: |
          file install/bin/doxybook2
          ldd install/bin/doxybook2

      - name: "List runtime dependencies(macOS)"
        if: runner.os == 'macOS'
        run: |
          file install/bin/doxybook2
          otool -L install/bin/doxybook2

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: "artifact-${{ matrix.suffix }}"
          path: install
          retention-days: 2
